# Recommender Systems HW 2 Item-Item Collaborative Filtering 

Marla 'Marlee' Goodman  9/28/2022

In [256]:
#import pandas
import pandas as pd

#read in CSV
df=pd.read_csv('https://raw.githubusercontent.com/MarlaGoodman/DAVRecommenderSystems/main/SitComs.csv')

#show df
df

Unnamed: 0  Parks&Rec  ModernFamily  TheOffice  Brooklyn99  BigBangTheory  \
0       Phil        3.0           3.0        NaN         1.0            5.0   
1       Ruth        1.0           NaN        NaN         1.0            NaN   
2       Jill        2.0           4.0        2.0         NaN            2.0   
3       Amy         5.0           3.0        4.0         5.0            5.0   
4        Ian        NaN           1.0        4.0         1.0            NaN   

   30Rock  
0     NaN  
1     NaN  
2     1.0  
3     3.0  
4     4.0

In [190]:
#rename respondent column to 'Respondent'
df.rename(columns = {'Unnamed: 0':'Respondent'}, inplace = True)

#show df
df

Respondent  Parks&Rec  ModernFamily  TheOffice  Brooklyn99  BigBangTheory  \
0       Phil        3.0           3.0        NaN         1.0            5.0   
1       Ruth        1.0           NaN        NaN         1.0            NaN   
2       Jill        2.0           4.0        2.0         NaN            2.0   
3       Amy         5.0           3.0        4.0         5.0            5.0   
4        Ian        NaN           1.0        4.0         1.0            NaN   

   30Rock  
0     NaN  
1     NaN  
2     1.0  
3     3.0  
4     4.0

In [9]:
#make Respondent column the index
df2=df.set_index('Respondent')

#show df2
df2

Parks&Rec  ModernFamily  TheOffice  Brooklyn99  BigBangTheory  \
Respondent                                                                  
Phil              3.0           3.0        NaN         1.0            5.0   
Ruth              1.0           NaN        NaN         1.0            NaN   
Jill              2.0           4.0        2.0         NaN            2.0   
Amy               5.0           3.0        4.0         5.0            5.0   
Ian               NaN           1.0        4.0         1.0            NaN   

            30Rock  
Respondent          
Phil           NaN  
Ruth           NaN  
Jill           1.0  
Amy            3.0  
Ian            4.0

In [10]:
# Get mean of every row and subtract all the means by the TV average
df_de_mean=df2.sub(df2.mean(axis=1),axis=0)
df_de_mean

Parks&Rec  ModernFamily  TheOffice  Brooklyn99  BigBangTheory  \
Respondent                                                                  
Phil         0.000000      0.000000        NaN   -2.000000       2.000000   
Ruth         0.000000           NaN        NaN    0.000000            NaN   
Jill        -0.200000      1.800000  -0.200000         NaN      -0.200000   
Amy          0.833333     -1.166667  -0.166667    0.833333       0.833333   
Ian               NaN     -1.500000   1.500000   -1.500000            NaN   

              30Rock  
Respondent            
Phil             NaN  
Ruth             NaN  
Jill       -1.200000  
Amy        -1.166667  
Ian         1.500000

In [11]:
#flip the dataframe
de_mean=df_de_mean.transpose()

de_mean

Respondent     Phil  Ruth  Jill      Amy   Ian
Parks&Rec       0.0   0.0  -0.2  0.833333  NaN
ModernFamily    0.0   NaN   1.8 -1.166667 -1.5
TheOffice       NaN   NaN  -0.2 -0.166667  1.5
Brooklyn99     -2.0   0.0   NaN  0.833333 -1.5
BigBangTheory   2.0   NaN  -0.2  0.833333  NaN
30Rock          NaN   NaN  -1.2 -1.166667  1.5

## Let's say we want to predict what Phil's rating of the Office would be

#### Scikit Learn

#### Find cosine similarities values for The Office and the other shows in Phil's column

#### Parks and Rec

In [111]:
#sim(Office,Parks&Rec)
#Office and Parks&Rec both have ratings from Jill and Amy
#PR values from Jill and Amy: -.2, .83333
#Office values from Jill and Amy: -.2, -.166667

# code copied from: https://www.datasciencelearner.com/sklearn-cosine-similarity-implementation/

# create vectors as numpy arrays
import numpy as np
arr_vec1 = np.array([[-.2,.83333]])
arr_vec2 = np.array([[-.2,-.166667]])

from sklearn.metrics.pairwise import cosine_similarity

sim_O_PR=cosine_similarity (arr_vec1,arr_vec2)
sim_O_PR

array([[-0.44322518]])

#### Modern Family

In [13]:
#modern family
de_mean.iloc[1:3]

Respondent    Phil  Ruth  Jill      Amy   Ian
ModernFamily   0.0   NaN   1.8 -1.166667 -1.5
TheOffice      NaN   NaN  -0.2 -0.166667  1.5

In [14]:
#values exist for both shows with users: Jill, Amy, and Ian

MF = np.array([[1.8,-1.166667,-1.5]])
O = np.array([[-.2,-.166667,1.5]])

sim_O_MF=cosine_similarity (MF,O)
sim_O_MF

array([[-0.60617848]])

#### Brooklyn 99

In [15]:
#Brooklyn99
de_mean.iloc[2:4]

Respondent  Phil  Ruth  Jill      Amy   Ian
TheOffice    NaN   NaN  -0.2 -0.166667  1.5
Brooklyn99  -2.0   0.0   NaN  0.833333 -1.5

In [16]:
B99=np.array([[-.166667,1.5]])
Of=np.array([[.833333,-1.5]])

sim_O_B99=cosine_similarity (B99,Of)
sim_O_B99

array([[-0.92244114]])

#### Big Bang Theory 

In [17]:
#BBT
de_mean.iloc[[2,4], :]

Respondent     Phil  Ruth  Jill      Amy   Ian
TheOffice       NaN   NaN  -0.2 -0.166667  1.5
BigBangTheory   2.0   NaN  -0.2  0.833333  NaN

In [18]:
BBT = np.array([[-.2,-.166667]])
Off = np.array([[-.2,.0833333]])
sim_O_BBT=cosine_similarity (BBT,Off)
sim_O_BBT

array([[0.46290182]])

#### 30 Rock

In [19]:
#30Rock
de_mean.iloc[[2,5], :]

Respondent  Phil  Ruth  Jill      Amy   Ian
TheOffice    NaN   NaN  -0.2 -0.166667  1.5
30Rock       NaN   NaN  -1.2 -1.166667  1.5

In [20]:
TR = np.array([[-.2,-.166667]])
Office = np.array([[-1.2,-1.166667]])
sim_O_30R=cosine_similarity (TR,Office)
sim_O_30R

array([[0.99706953]])

All the cosine similarities between the Office and the other shows:

In [21]:
print(sim_O_PR)
print(sim_O_MF)
print(sim_O_B99)
print(sim_O_BBT)
print(sim_O_30R)

[[-0.44322518]]
[[-0.60617848]]
[[-0.92244114]]
[[0.46290182]]
[[0.99706953]]


The Office has the best similarity value with 30 Rock. The second most similar is the Big Bang Theory. The rest are negative. 

30 Rock does not have a rating from Phil, so we need to look at Phil's rating for the Big Bang Theory, which is a 5. 

If the other cosine similarites had been positive, we could have used those TV show ratings from Phil to calculate a weighted average rating for Phil for the Office.

Or, if 30 Rock had a rating from Phil, we could have used that TV show rating along with his Big Bang Theory rating to calculate a weighted average for him for the Office.

Since neither is the case, we just have to use his Big Bang Thoery rating and apply it to his predicted rating for the Office - 5. 

#### LightFM

In [207]:
!pip install lightfm

In [208]:
#import LightFM
from lightfm import LightFM

In [234]:
#fill dataframe nulls with 0
#(I tried LightFM functions and they wouldn't work with null values)
df3=df2.fillna(0)

#turn into sparse matrix
#code taken from: https://stackoverflow.com/questions/20459536/convert-pandas-dataframe-to-sparse-numpy-matrix-directly
matrix=scipy.sparse.csr_matrix(df3.values)


In [236]:
# can't get this work for me
print(repr(matrix['train']))
print(repr(matrix['test']))

IndexError: Index dimension must be <= 2

In [ ]:
#so try the test/train function from scikit learn 
from sklearn.model_selection import train_test_split

train, test = train_test_split(matrix, test_size=0.2)

In [224]:
train

<4x6 sparse matrix of type '<class 'numpy.float64'>'
	with 15 stored elements in Compressed Sparse Row format>

In [225]:
test

<1x6 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [237]:
#code taken from: https://github.com/lyst/lightfm/blob/master/examples/quickstart/quickstart.ipynb
    
model = LightFM(loss='warp')
%time model.fit(train, epochs=30, num_threads=2)

CPU times: user 18.8 ms, sys: 9.17 ms, total: 28 ms
Wall time: 46.9 ms


In [238]:
from lightfm.evaluation import precision_at_k

In [243]:
print(precision_at_k(model, train, k=5).mean())

0.75


In [244]:
#At this point, I ran out of time to finish the assignment.
#I would take more time to see what the issue is here, and explore Max Humber's work more.
# It provides more details on sparse matrices, which is more similar to my data 
#(ie it's not a given movie data set)
print(precision_at_k(model, test, k=5).mean())

ValueError: Incorrect number of features in user_features

The main difference for collaborative filtering between scikit learn and Light FM, at least from what I understood for the assignment, is: Scikit learn makes use of cosine similarities, distances, and weighted averages to make predictions, while Light FM uses trains some data and then tests the model. If the model is good, it will make predictions that way.